services:

  server:
    # image for golang server
    image: golang:1.14.2-alpine3.11
    container_name: "warehouse"
    build: ./
    command: ./app
    ports:
      - 8000:8000
    # depends_on:
    #   - mongodb

  # mongodb:
  #   image: mongo:latest
  #   container_name: "mongodb"
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #     - MONGODB_DATABASE=testdb
  #   volumes:
  #     - ./.data/db:/data/db
  #   ports:
  #     - 27017:27017
  #   command: mongod --smallfiles --logpath=/dev/null # --quiet